name: build

on:
  push:
    paths: [ '.github/workflows/**','src/**']
  pull_request:
    paths: [ '.github/workflows/**','src/**']

jobs:
  buildlunahook:
    uses: ./.github/workflows/buildlunahook.yml
  
